### ISSUE TITLE
Cannot use character vector as value for fl parameter

### ISSUE THREAD

**Issue by FrieseWoudloper** [uRos2018/nlgeocoder#2]
You cannot specify multiple fields for the fl parameter.

`res <- nl_geocode("Martinikerkhof 3 Groningen", fl = c("woonplaatsnaam", "centroide_ll", "centroide_rd"), messaging = TRUE)`

The code above generates the wrong request:

https://geodata.nationaalgeoregister.nl/locatieserver/v3/free?fq=type:adres&q=Martinikerkhof%203%20Groningen&fl=c(%22woonplaatsnaam%22,%20%22centroide_ll%22,%20%22centroide_rd%22)

It results in a HTTP 400 error:

```
"Error parsing fieldname: Unknown function c in FunctionQuery('c(\"woonplaatsnaam\", \"centroide_ll\", \"centroide_rd\")', pos=2)"
--
code | 400
```

**Comment by edwindj** [comment]
Should be fixed
