### ISSUE TITLE
Add minZoom to addPDOKTiles

### ISSUE THREAD

**Issue by FrieseWoudloper** [uRos2018/nlgeocoder#4]
The minimum zoomlevel of the PDOK files is 6. It would be nice to add that to the addTiles part:
`options = tileOptions(minZoom = 6, maxZoom = 18)`

**Comment by edwindj** [comment]
is fixed in the development version of nlgeocoder (> 0.1.3).
@FrieseWoudloper Can you check if it works? (it does on my machine :-) )

**Comment by FrieseWoudloper** [comment]
Works fine now! Thank you for fixing this issue.
